name: Build AppImage and .deb

on:
  push:
    tags:
      - '*'  # Trigger on any tag (with or without 'v' prefix)
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          python3-dev \
          python3-pip \
          libopencv-dev \
          libusb-1.0-0-dev \
          pybind11-dev \
          nlohmann-json3-dev \
          pkg-config \
          wget \
          devscripts \
          debhelper \
          python3-pil \
          python3-tk

        # Install pybind11_json header
        echo "Downloading pybind11_json.hpp..."
        sudo wget -O /usr/local/include/pybind11_json.hpp \
          https://raw.githubusercontent.com/pybind/pybind11_json/master/include/pybind11_json/pybind11_json.hpp

        pip3 install pyinstaller pillow pystray

    - name: Download appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
        sudo apt-get install -y libfuse2

    - name: Build project and AppImage
      run: |
        mkdir build
        cd build
        cmake ..
        make lcd_driver
        export ARCH=x86_64
        make appimage
      env:
        ARCH: x86_64

    - name: Build .deb package
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j"$(nproc)" lcd_driver
        cd ..
        debuild -us -uc -b
        VERSION=$(head -n1 debian/changelog | awk '{print $2}' | tr -d '()')
        mv ../tr-driver_${VERSION}_amd64.deb build/ || true
        echo "Built: tr-driver_${VERSION}_amd64.deb"

    - name: Extract version from changelog
      id: version
      run: |
        VERSION=$(head -n1 debian/changelog | awk '{print $2}' | tr -d '()')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Detected version: ${VERSION}"

    - name: List generated files
      run: |
        ls -lh build/*.AppImage || true
        ls -lh build/*.deb || true

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/tr-driver-*.AppImage
          build/tr-driver_*_amd64.deb
        body: |
          ## LCD System Monitor Release ${{ steps.version.outputs.version }}
          
          ### Installation
          #### 🖥️ AppImage
          1. Download: `tr-driver-*.AppImage`
          2. Make executable: `chmod +x tr-driver-*.AppImage`
          3. Run: `./tr-driver-*.AppImage`
          
          #### 📦 Debian package
          1. Download: `tr-driver_${{ steps.version.outputs.version }}_amd64.deb`
          2. Install: `sudo dpkg -i tr-driver_${{ steps.version.outputs.version }}_amd64.deb`
          3. Run: `tr-driver`
          
          ### Changes
          See [CHANGELOG.md](CHANGELOG.md) for details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts (for non-tag builds)
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/tr-driver-*.AppImage
          build/tr-driver_*_amd64.deb
        retention-days: 30
